### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by PhilipChicco** [ThoroughImages/CAMEL#2]
Hi. 

Thanks for the great work. Will you host the dataset on a different platform in future? Currently, without a Chinese phone number or ID , I am unable to download your dataset. Any recommendations on how to download the data in this case?

Thank you

**Comment by physicso** [comment]
Hi,

Upon your request, we have uploaded the dataset to Google Drive, which can be found at:
https://drive.google.com/open?id=1brr8CnU6ddzAYT157wkdXjbSzoiIDF9y

Thank you very much for your interest in our work.
Shuhao
